#!/bin/sh -x
set -e
test -e wv/Makefile || ./get-git-modules

rm -f config.mk
cat >config.mk <<EOF
	BUILD_TARGET=win32
EOF

(cd dbus-sharp && ./autogen.sh && ./configure)
(cd wv && ./configure-mingw32) || exit $?

# Not needed on win32
#(cd vxodbc && make configure && ./configure) || exit $?
