WVDOTNET=../wvdotnet
include $(WVDOTNET)/monorules.mk

all: wvdbus-sharp.dll

CSFLAGS=/unsafe

wvdbus-sharp.dll: \
	assemblyinfo.cs \
	Address.cs \
	Authentication.cs \
	Bus.cs \
	BusObject.cs \
	Connection.cs \
	DBus.cs \
	DProxy.cs \
	ExportObject.cs \
	Introspection.cs \
	IntrospectionSchema.cs \
	Mapper.cs \
	MatchRule.cs \
	Message.cs \
	MessageFilter.cs \
	MessageReader.cs \
	MessageWriter.cs \
	PendingCall.cs \
	Protocol.cs \
	Server.cs \
	Signature.cs \
	SocketTransport.cs \
	Transport.cs \
	TypeDefiner.cs \
	TypeImplementer.cs \
	UnixMonoTransport.cs \
	UnixNativeTransport.cs \
	UnixTransport.cs \
	Wrapper.cs

